version: "3"

services:
  node:
    image: node:18.0.0-alpine
    user: node
    working_dir: /home/node/source
    tty: true
    stdin_open: true
    ports:
      - 2105:5173
    volumes:
      - .:/home/node
    command: sh -c "npm install && npm run dev --host"